// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PXEadllqpXyy1QCPD8wQ7N-MXRghGWo',
    appId: '1:527317256858:android:5b4a74da69c6a35cb52d23',
    messagingSenderId: '527317256858',
    projectId: 'indoormaps-43bcc',
    databaseURL: 'https://indoormaps-43bcc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'indoormaps-43bcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ugPJAWWa-r0EPEv42TNtIQaioTzWZqU',
    appId: '1:527317256858:ios:832c80939b08fd40b52d23',
    messagingSenderId: '527317256858',
    projectId: 'indoormaps-43bcc',
    databaseURL: 'https://indoormaps-43bcc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'indoormaps-43bcc.appspot.com',
    iosClientId: '527317256858-nhvf1h7kglc1udgkbnrncgki3kp420uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.indoorLocalizationApp',
  );
}
